OpenDevicePartnership/embassy-imxrt

src/flash.rs
When there is any system context changing operation, we would want next set of instructions including memory access instructions to execute with the new settings created by the context changing operation.
We use DSB to synchronize the instruction pipeline where every instruction after DSB will execute after all the instruction before the DSB. This is done to make sure, when we flush the pipeline with ISB, it happens once the context changing operation is completed.
Then comes ISB to cleanup the CPU pipelines. After that, CPU fetches the instructions again from the memory. Since Cortex M series do not have instruction cache, the instructions are fetched from the memory directly.
=> Fixed barrier instruction sequence

examples/rt633/rt633.yaml
probe-rs 0.27.0 changed the format of chip description files. Now we must tell the version of the access port.
=> [BREAKING] Update rt633.yaml

Cargo.toml, examples/rt685s-evk/src/bin/crc.rs, src/crc.rs
If `Config` fields are not public, nobody can set a different configuration.
While at that also make sure to use the new WR_DATA size accessors to ensure that the correct CRC is computed.
=> crc: make Config fields public & use new WR_DATA size accessors

.github/workflows/rolling.yml
We must pass the correct flags for the rolling workflow as well, otherwise a `chip` module won't exist. D'oh.
=> rolling: allow rolling to work again

examples/rt685s-evk/src/bin/crc.rs, src/crc.rs
Reverse In, Complement In, Reverse Out, and Complement Out are more standard names used elsewhere. Let's match the naming convention to make it easier for those using this driver.
While at that, also add tests for all three CRC types supported.
=> crc: use more standard names for configuration parameters

examples/rt685s-evk/src/bin/timer.rs, src/timer.rs
**Why?**
To calculate fan speed, we need to capture fan TACH signal period time, from this rising edge to next rising edge.
**What changes?**
1. Implement new function "capture_cycle_time_us" for CaptureTimer. This function trigger capture twice and return time us between these two captures.
2. Fix return value in "get_event_capture_time_us".
**How to test?**
Result from print log match with LA waveform
From print log
11:04:48.115 : (86918650) fan tach cycle 4355 us
11:04:48.147 : (86918650) calculated fan rpm = 6888
LA waveform of fan tach pin
#170
=> Update CaptureTimer to calculate fan speed

src/espi.rs
SRST appears to be required on port complete as, without it, transfers get wedged.
=> espi: set SRST bit on port complete

src/chips/mimxrt633s.rs, src/chips/mimxrt685s.rs, src/flexcomm.rs, src/i2c/mod.rs, src/iopctl.rs
- Adding https://github.com/OpenDevicePartnership/embassy-imxrt/pull/235 to enable FC14 and FC15
- Changes in I2C module to support FC15 I2C master
@tullom FYI
=> Add support for FC14 SPI (Untested) and FC15 I2C

examples/rt685s-evk/src/bin/dma-mem.rs, src/dma/mod.rs, src/hashcrypt/mod.rs, src/i2c/master.rs, src/i2c/mod.rs, src/i2c/slave.rs, src/uart.rs
Closes #327 
Some kicking off questions:
- The reason I need to make a `new_async_nodma()` fn instead of hijacking `new_async()` is because `new_async()` requires a dma_ch object that impls Peripheral and impls an interrupt with `MasterDma`. I tried creating structs to impl all that but I hit a wall.
- I added documentation saying NOT to use this and to prefer `new_async()`, except in the cases of the Flexcomm not having DMA support. Is this enough or do you think this should be gated behind some sort of feature flag to reduce the possibility of misuse?
EDIT: 
I was able to create a NoDma structure. I had to minimally modify the DMA api, specifically `reserve_channel()` now returns an option that will return None if NoDma is used.
=> Add NoDma I2C master async bus implementation

src/adc.rs, src/crc.rs, src/dma/mod.rs, src/espi.rs, src/flexcomm.rs, src/gpio.rs, src/hashcrypt/mod.rs, src/i2c/master.rs, src/i2c/mod.rs, src/i2c/slave.rs, src/lib.rs, src/pwm.rs, src/rng.rs, src/time_driver.rs, src/timer.rs, src/uart.rs, src/wwdt.rs
commit d41eeeae79388f219bf6a84e2f7bde9f6b532516 in upstream embassy renamed the PeripheralRef struct to Peri and removed the Peripheral trait in favor of a new PeripheralType trait.
This commit makes sure that we can still compile our HAL with latest embassy upstream.
=> Fixed recent regressions caused by upstream changes

src/dma/channel.rs, src/espi.rs, src/i2c/master.rs, src/rng.rs, src/uart.rs
This is a defensive move to ensure that wakes are not ever lost, if the event we are waiting for happens AFTER checking, but BEFORE (re-)registering a waker, which can happen with interrupts.
In general, "Register, then check" is the pattern that should be used to avoid potential race conditions.
There are two cases I was not sure about:
* dma::channel seems to check twice, once before and once after registering, it is likely fine to just register and then check once.
* `rng` does a slightly more complicated check, potentially not unmasking interrupts. This might also be able to be simplified.
=> Move waker registrations PRIOR to condition checking

src/i2c/slave.rs
This is harmless, if the slave is in the wrong state, it will just fail later, but this allows i2c slave state machine to be more robust if due to misuse of slave API, the slave is already past the addressed state.
--------------------------------------
This was exposed by an unexpectant use of the i2c slave API.
Normally we expect `respond_to_write()` to be invoked until it returns `Complete` to complete an I2C transaction, then `listen()` is invoked to wait for the next transaction.
However, in this case, due to a misunderstanding of the i2c slave API, `listen()` was invoked before `respond_to_write()` returns `Complete`. Causing the STOP for the previous i2c transaction to be interpreted as the STOP for the current ongoing transaction and thus thinking the current transaction is an …
=> i2c slave: relax state machine restriction

src/uart.rs
Adds drop guards for UART for cancellation safety, similar to #367.
I also noticed that interrupts were never enabled when calling `Uart::new_async`, and that there were tabs in the macros, so I fixed those as well.
=> Add UART drop guards

src/uart.rs
set_uart_config() does a regs.cfg().write() which overwrites the regs.cfg().modify(|_, w| w.ctsen().enabled()); done earlier
=> Fix UART CTS 

src/i2c/slave.rs
This fixes i2c blocking slave functions not returning until the next operation starts.
=> Ensure I2C blocking slave polling stops on deselect as well.

.github/workflows/check.yml, supply-chain/README.md, supply-chain/audits.toml, supply-chain/config.toml, supply-chain/imports.lock
Initializing `cargo vet` for this repository. This allows us to audit the third party dependencies being used in the code.
- As part of initialization, all current dependencies are under exemptions. These need to be audited as time permits.
- We import audits from Mozilla and Google. Dependencies that have been already audited by either of them are added to `imports.lock` file by `cargo vet`
A new workflow is also being added to run `cargo vet` on any new PR
Closes #362
=> Cargo vet init

examples/rt685s-evk/Cargo.lock, examples/rt685s-evk/Cargo.toml
Note for reviewer: perhaps the same is the case for the rt633 examples, but I have no access to that chip.
=> Upgrade mimxrt600-fcb to 0.2.2 for the rt685 examples, as those don't work with 0.2.0 (won't boot)

.github/workflows/check.yml, .github/workflows/nostd.yml
Since we're checking in cargo.lock into the repo, it is expected that it builds with the dependencies listed in the lock file.
Updating GitHub workflows to use the locked dependencies ensures that the build is reproducible.
=> Update actions to use cargo.lock for dependencies

src/crc.rs
Add reconfigure_new function to reuse Crc object with new algorithm. This sets the Config object to the input and reconfigures the registers. Used in a CRC platform service, under development.
=> Add CRC reconfigure_new function to reuse object with new algorithm

supply-chain/config.toml
Description copied from https://github.com/OpenDevicePartnership/embedded-services/pull/246
Exactly applicable to this repository as well.
`cargo vet` is primarily to audit third party dependencies from crates.io
Since embassy crates are also published on crates.io but we're using the GitHub versions, this leads to some issues.
If we mark them to have the same audit criteria as applied to other crates `audit-as-crates-io = true`, it would mean that we need to audit new versions of the dependencies every time cargo.lock is updated, which is pretty frequent for a GitHub based dependency as it uses the commit hash of the HEAD.
If we don't include them in config.toml, it results in a vet failure as matches are found on crates.io, but they don't match with what we're using.
The alternative is …
=> Avoid vetting embassy dependencies pulled from GitHub

deny.toml
A new security advisory was posted this morning for the atomic-polyfill crate, which is now unmaintained, with the authors suggesting to switch to using portable-atomic instead.  It looks like we don't have a direct dependency on atomic-polyfill, though - rather, we have this dependency chain:
+ atomic-polyfill v1.0.3
+-- heapless v0.7.17
+-- postcard v1.1.1
+-- embedded-services v0.1.0
+-- storage_bus v0.1.1
+-- embassy-imxrt v0.1.0
It looks like there's already a new version of heapless (0.8.0) that has made the switch, but postcard has not been updated to consume it yet because it's a breaking change.  It sounds like the author of postcard is aware of the issue as of today and is looking into a fix (https://github.com/jamesmunns/postcard/issues/223)
Until then, our gates are broken on …
=> Temporarily suppress deprecation warning for RUSTSEC-2023-0089

examples/rt685s-evk/src/bin/rtc-time.rs, src/time_driver.rs
Commit 8f9b05cd2688eae443473cfd6fce6897fcd06475 changed the return type of RtcDatetime::get_datetime() from (Datetime, Result<(), Error>) to Result<Datetime, Error>, but it missed the example that leverages get_datetime. This change fixes the example so it compiles and derives Debug for the error type so that Result::unwrap() can be used.
=> Fix build for rtc-time example

Cargo.lock, Cargo.toml, examples/rt633/Cargo.lock, examples/rt685s-evk/Cargo.lock, examples/rt685s-evk/src/bin/i2c-loopback-async-10bit.rs, examples/rt685s-evk/src/bin/i2c-loopback-async.rs, examples/rt685s-evk/src/bin/i2c-master-async.rs, examples/rt685s-evk/src/bin/i2c-master.rs, src/i2c/master.rs, src/i2c/mod.rs, supply-chain/config.toml, supply-chain/imports.lock
This change enables configuring the duty cycle for the I2C bus by specifying the number of clock cycles that the clock line will be asserted high/low by the I2C master device
Closes #267
=> Make I2C duty cycle configurable

src/espi.rs
The following is sequence of events for handling SCI
- MCU wants to assert SCI so we clear the SCIN bit in WIREWO
- I see VWire event 0x6 data 0x16 on the host indicating SCI event
- Host does a Peripheral Read to get the SCI related data
- Host sends interrupt to detail with the SCI internally on apps side
- Host sends a peripheral write to clear the SCI
- MCU receives peripheral write and writes SCIN --> 1 in WIREWO
- Host receives VWire event 0x6 data 0x17 indicating SCI is cleared
- WIREWO will read indicating SCIN  --> 1 only after host ACK's the VWire data
The MBINTALL must be set by default otherwise only the first read/write packets will generate interrupts.
=> Set MBINTALL by default for eSPI and allow sci to be cleared or set

src/i2c/mod.rs
Some of FLEXCOMM5 I2C pins were mapped to a wrong function.
=> fix the i2c functions for FLEXCOMM5 pins

supply-chain/README.md, supply-chain/config.toml, supply-chain/imports.lock
ODP rust crate audits are expected to be present in the rust-crate-audits repository. This PR enables importing those audits via `cargo vet`. This allows us to maintain a central audit repository, while using the same crates across ODP repositories.
The README is also being updated to reflect the change.
=> Pull audits from rust-crate-audits

.github/workflows/check.yml, ci.sh
CI was starting to limit the amount of variations we could run in cargo hack. Instead, let's make a script that runs within CI and relies on cargo-batch to run all variations.
While at that, also make sure to add RTC timer as a variant.
=> Move cargo-hack to a script

src/time_driver/ostimer.rs
Before writing to MATCH_L/MATCH_H registers, wait for permission to do so by pollinmg MATCH_WR_RDY bit in CTRL register.
=> timer: ostimer: wait for match write ready

src/clocks.rs
Calibrate the divisor to make sure we get as close as possible to the
requested delay.
While at that, also rename the frequency argument to `freq_hz` as
that's what the method expects. Additionally, update rustdoc to
further explain how the method is supposed to work.
=> Calibrate delay loop clocks

CODEOWNERS, supply-chain/README.md, supply-chain/config.toml
This pull request updates a number of things for `cargo vet` deployment.
- Updated CODEOWNERS to include the `crate-auditors` team whenever any files in the cargo vet folder (supply-chain) is updated
- Updated README to describe audit criteria in more detail
- Added new policies for `embassy-embedded-hal`, `embedded-batteries` and `embedded-batteries-async` crates
Closes #395
=> Add codeowners for cargo vet, new crate policies and update README

examples/rt685s-evk/Cargo.lock, examples/rt685s-evk/Cargo.toml, examples/rt685s-evk/src/bin/keyboard.rs
Simple example using my minimal 4x4 keymatrix. Note that `keyberon` sort of expects a `usb_device` to be available such that it can send HID reports. Because we don't have that (yet?), for now I'm just dumping the data through `defmt-rtt` and, to reduce console spamming, only when the report is not empty.
=> Add simple keyboard example

Cargo.toml, src/lib.rs, src/rtc.rs, src/time_driver/rtc.rs
The RTC driver and RTC time driver both accessed the registers without synchronization.  This led to an issue where writes to the control register could be 'lost'.
This was possible in 'safe' code because the `rtc()` function was not marked `unsafe`, despite being unable to enforce the invariant that the critical section must be held while writing to the control register.
This change addresses the problem with a few fixes:
- Makes the RTC driver and RTC time driver mutually exclusive to avoid the muddled ownership semantics for the RTC hardware
- Makes the `rtc()` functions `unsafe` to reflect that they cannot uphold the synchronization requirement on the ctrl register.
- Fixes a bug in the RTC time driver that caused it to panic due to an underflow if a prior firmware on the device wrote …
=> RTC driver / time driver: fix soundness bug

Cargo.lock, src/rng.rs, supply-chain/audits.toml, supply-chain/config.toml
RNG is failing with frequency check when main clock is running at a high clock rate (beyond 16 MHz). NXP acknowledged there is an issue with the HW entropy test at higher clock rates and recommended to disable HW entropy test + implement SW entropy test.
NXP HW test disabling code snippet:
```c
void disable_HW_test(void)
{
/* Turn off TRNG self test */
TRNG0->MCTL |= TRNG_MCTL_PRGM(1); //Enable MCTL[PRGM] to change to Programming mode
TRNG0->MCTL |= TRNG_MCTL_TRNG_ACC(1); //Enable MCTL[TRNG_ACC] access mode
TRNG0->FRQMIN = 0x00000000;
TRNG0->FRQMAX = 0xFFFFFFFF;
TRNG0->PKRMAX = 0x0000FFFE;
TRNG0->PKRRNG = 0x0000FFFF;
TRNG0->SCML   = 0xFFFFFFFE;
TRNG0->SCR1L  = 0x7FFF7FFE;
TRNG0->SCR2L  = 0x3FFF3FFE;
TRNG0->SCR3L  = 0x1FFF1FFE;
TRNG0->SCR4L  = 0x0FFF0FFE;
TRNG0->SCR5L  = 0x07FF07FE; …
```
=> rng: add recovery from error and disable HW test

examples/rt685s-evk/src/bin/i2c-loopback-async-10bit.rs, examples/rt685s-evk/src/bin/i2c-loopback-async.rs, examples/rt685s-evk/src/bin/i2c-master-async.rs, examples/rt685s-evk/src/bin/i2c-slave-async.rs, examples/rt685s-evk/src/bin/i2c-slave.rs
Tracing before timer is initialized is bad new because defmt needs timestamps, so don't do that.
=> i2c examples: remove traces before initialization

src/flexspi/nor.rs
IDATSZ affects read and write in this way:
IDATSZ is 16-bits:
**So max transfer size per command is u16::max.**
**IPCMDDONE should be check after data transfer is done and it needs to be clear so it is not sticky:**
=> Fix flexspi max transfer size per command and command done checking ordering issue

src/flexspi/nor.rs
All bitfields in this INTR are write 1 to clear, read-modify-write will accidentally clear other bits that are set.
=> flexspi: INTR should not do read-modify-write

.github/workflows/check.yml, ci.sh, examples/rt633/Cargo.lock, examples/rt633/src/bin/espi.rs, examples/rt685s-evk/src/bin/i2c-master.rs, src/espi.rs, src/flexspi/nor.rs, src/gpio.rs, src/i2c/master.rs, src/time_driver/ostimer.rs, src/timer.rs
Clippy workflow was not checking errors and failing silently, and it let a bunch of clippy errors through.
- Rework the clippy check job because of the silent failure and `embassy-imxrt` needs to have chip feature defined to compile correctly.
- Fix up all the clippy errors.
- Fix up another example that traces before initialization of `embassy-imxrt`
=> Fix clippy check job and fix up examples

src/clocks.rs
When implementating the bootloader, walked head-first into the problem that the clock domain configuration is partially implemented. See https://github.com/OpenDevicePartnership/embassy-imxrt/issues/477 .
For now, I quickly added setting the mainclk source. For the bootloader I require a slower main clock. This PR should not change the default behaviour.
=> Added mainclk source selection

Cargo.lock, Cargo.toml, examples/rt633/Cargo.lock, examples/rt633/Cargo.toml, examples/rt685s-evk-performance-tracing/Cargo.lock, examples/rt685s-evk-performance-tracing/Cargo.toml, examples/rt685s-evk/Cargo.lock, examples/rt685s-evk/Cargo.toml, supply-chain/audits.toml, supply-chain/config.toml
This fixes the panic caused by the switch to crates.io versions of embassy crates.
```
1308.443201 [ERROR] panicked at C:\Users\febalbi\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\embassy-executor-0.7.0\src\raw\waker.rs:38:9:
Found waker not created by the Embassy executor. `embassy_time::Timer` only works with the Embassy executor. (panic_probe panic-probe-0.3.2/src/lib.rs:104)
```
=> finalize transition to crates.io

Cargo.toml
Embedded-mcu-hal has the default feature 'defmt' enabled. We are using the default feature set of this crate, hence we have a dependency on defmt for this crate as well.
This PR removes this dependency and adds it to the defmt feature instead.
=> Remove dependency on defmt from embassy-imxrt

.github/workflows/check.yml, ci.sh
This pull request updates the Clippy linting configuration in both the GitHub Actions workflow and the CI script to ensure that specific lint categories are treated as errors, and improves the setup of the Rust toolchain for CI. The main changes are focused on enforcing stricter linting and ensuring the correct components are installed for Rust CI jobs.
**Linting configuration improvements:**
* Updated `cargo clippy` commands in `.github/workflows/check.yml` and `ci.sh` to use `-D` (deny) instead of `-F` (forbid) for specific Clippy lint categories (`clippy::suspicious`, `clippy::correctness`, `clippy::perf`, `clippy::style`), ensuring these are treated as errors during CI runs. [[1]](diffhunk://#diff-55f05888fd854d9962bdd4d8ccf23a07b610990f58174397b2586b58f8937428L82-R82) …
=> Fix intermittent ci failure
