OpenDevicePartnership/embassy-imxrt

examples/rt685s-evk/src/bin/i2c-master-async.rs
src/i2c/master.rs

According to NXP, mststate is only accurate and reflect actual HW state
when pending is set. This causes race condition where if the previous
transaction gets an address nack, the next transaction still sees
address nack in the mststate. Checking pending bit first ensure that
mststate is updated already.

Fix address nack race condition

---

CODEOWNERS

No functional changes, just making sure Matteo and Robert and can also approve PRs.

Add Matteo and Robert as CODEOWNERS

---

Cargo.toml
README.md

Getting ready for integration in upstream embassy project.

improve crate documentation

---

examples/rt685s-evk/src/bin/benchmarking-gpio.rs
examples/rt685s-evk/src/bin/benchmarking-system-peripheral.rs

This PR: https://github.com/OpenDevicePartnership/embassy-imxrt/pull/254 somehow got closed when repo was transitioned to be open to the public.

Add benchmarking examples using DWT/systick/GPIO pin toggling

---

src/i2c/master.rs

For buffer of size N, i2c master sends a NACK on (N+1)th byte instead of Nth byte. This change separates the read operation into two steps. The first N-1 bytes are read using DMA and the last byte is read manually, which generates the expected NACK at Nth byte.
For a single byte read operation, the DMA is bypassed and the byte is read manually.
Closes #304

Optimize i2c read by handling the last byte manually

---

Cargo.toml
examples/rt633/src/bin/espi.rs
src/espi.rs
src/timer.rs

Expose VWire API for the application.

Espi VWires

---

examples/rt633/src/bin/espi.rs
src/espi.rs

Add support for Mailbox Split port configuration.

eSPI mailbox split

---

src/uart.rs

In current Uart code, it only accepts 115200. If we set it to 3000000 or 4000000, the whole system will crash.
We need 3 changes to fix it:
Open clock setting to have user to set different type, for example: FFRO. Now it is hardcoded as SFRO.
Open source clock setting in Hz, in our PTL program, we need to set it as 48M, but it is hardcoded as 16M Hz.
There is a bug in current code to calculate brgval.
let brgval = (source_clock_hz / ((osrval + 1) * baudrate)) - 1;
if source_clock_hz is 48M and baudrate is 4M, osrval is 15, brgval is be -1, since the type is u32, it cannot be accept by rust, it will return error.
Need to use compare the number instead of compare it with FFFF.
I tested it in my device by setting 4M baudrarte, it can work as expected.

Fix cannot set UART baudrate to those value other than 115200 issue

---

src/espi.rs

After review of NXP part the proper sequence is first to wait for configuration to be completed and platform reset to be cleared before doing any other actions.
Added wait_for_plat_reset function that clients should wait for before doing further communication.
Added support for OOB mailbox and validated we can receive OOB packets. Future change coming to send OOB packets from MCU to host as well.

Added support for OOB and removed SRST added wait_for_plat_reset

---

src/espi.rs

The eSPI service needs to populate data into the correct eSPI memory area and specify the port and length of data to send.
Calling oob_read_start will send VWire event to the host to cause it to trigger a read of the data that is already loaded. After the host has finished reading the data it will send back an INTRD event on the corresponding port to indicate the read has completed.
The eSPI service must not trigger a new read until the previous read has completed.

Added support to trigger OOB read to host

---

examples/rt685s-evk/Cargo.lock
examples/rt685s-evk/Cargo.toml
examples/rt685s-evk/memory.x

CC @felipebalbi @JamesHuard 
Follow up to #386 #385

Update FCB, enable debug info, replace tabs with spaces in memory.x

---

src/i2c/mod.rs

In #367 I added remediation driven by the interrupt when a transaction was cancelled. However, I placed both the master/controller remediation and slave/target remediation under the `mstpending` event, where the slave remediation needs to be triggered when the `slvpending` event occurs.
This was caught by @davidv1992 on review.

Fix i2c remediation

---

examples/rt685s-evk/src/bin/flexspi-storage-service.rs
src/flexspi/mod.rs
src/flexspi/nor.rs
src/lib.rs

Flexspi Cleanup

---

src/time_driver.rs

The Datetime code had a couple bugs in the datetime -> seconds-since-epoch conversion code that caused it to be off by a day or two in leap years. These occurred because when looking at whether to account for a leap year, they were evaluating the previous year/month rather than the current year/month. This changes the logic to correctly account for leap years.

Fix time conversion bug in Datetime code

---

.github/workflows/check.yml

With this change, the PR policy for this repo will switch from merge commits to squash commits. Please keep your PR small so we are git bisecting over smaller changes.

check.yml: remove per commit checking

---

src/clocks.rs

This PR resets the main clock source to FFRO divided by 4 before changing the PLL configuration.
When a bootloader and payload application both use `embassy-imxrt`, the clock configuration routine is ran twice. The second time, the PLL will be reset while it's also being used as a main clock source. The result is that the CPU stops executing instructions and even the debug probe gets disconnected (which made this a bit difficult to debug :sweat_smile:).
By resetting the main clock source to the reset default, we can safely re-configure the PLL, and then switch (back) to it.

Make sure we're not using the PLL as main clock when resetting it.

---

examples/rt685s-evk/src/bin/button.rs

RT685 EVK has two buttons on-board. Use them.

Add a simple button example

---

src/hashcrypt/hasher.rs

It turns out that we had a race condition between the time we read STATUS register and the DMA actually starting the transfer. If we modify the driver such that we use HASHCRYPT interrupts for errors and digest ready, we avoid the race condition altogether and the example works in both dev and release modes.
Note that, ideally, `transfer()` would produce a `Result` to indicate the possible error condition. Because that would result in a breaking change, this PR is only fixing the bug and assuming the error condition never triggers, which is no different from what the driver was already doing anyway.
Fixes #248

examples: fix sha256-async hang in release mode

---

src/timer.rs

FieldWriter::bits() will clear field first, than write new value, cause PWM stay low for a period.
Since MATCH field is 32 bits, so we can use REG::bits to workaround the problem.

Update CTimerPWM::set_duty() to fix PWM bouncing when duty change

---

src/lib.rs

- Refactored interrupt handler macro to delegate to a helper function (`__handle_interrupt`) for conditional tracing.
- Moved all `#[cfg(feature = "systemview-tracing")]` logic out of the macro and into the helper function, ensuring correct evaluation in the defining crate.
- Added required trait bound `T: crate::interrupt::typelevel::Interrupt` to `__handle_interrupt` for trait compliance.
- This eliminates downstream cfg warnings and keeps macro-generated code clean and portable.

move systemview-tracing cfg out of macro and into helper function

---

src/time_driver/ostimer.rs

Previous builds with debug enabled we saw cases where after checking timestamp <= t and before the new MATCH and INTENA was written out COUNT_VALUE went passed timestamp and timer interrupt stopped firing.
I did some testing and validated even if MATCH value is written but INTENA=0 the INTRFLAG will not be latched and interrupt will not fire.
To guarantee that the interrupt will fire we must have all the following completed
MATCH value is latched into the shadow registers
INTENA = 1
Current COUNT_VALUE < timestamp
To ensure these are all correct we first disable timer interrupts and clear any previously pending interrupt.
Writes to the INTRFLAG are async so we must wait for the WR_RDY bit to be set before writing to MATCH
Write the new MATCH value
Write INTENA to re-enable timer interrupt …

Fix missing ostimer interrupts

---

examples/rt685s-evk/Cargo.lock
examples/rt685s-evk/Cargo.toml
examples/rt685s-evk/src/bin/spi-async.rs
examples/rt685s-evk/src/bin/spi-loopback.rs
examples/rt685s-evk/src/bin/spi.rs
src/lib.rs
src/spi.rs

Add blocking and async SPI drivers for RT600 series of MCUs.

Add SPI driver
